name: dry-struct
codacy_id: 961f5c776f1d49218b2cede3745e059c
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Typed structs and value objects"
  development_dependencies:
    - bundler
    - rake
    - rspec
    - yard
  runtime_dependencies:
    - [zeitwerk, "~> 2.6"]
    - [dry-core, "~> 1.0", "< 2"]
    - [dry-types, ">= 1.7", "< 2"]
    - [ice_nine, "~> 0.11"]
